# Generated by Django 3.1.7 on 2021-07-08 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coregis', '0002_corecity_population'),
    ]

    operations = [
        migrations.CreateModel(
            name='catObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='urbanObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('comment', models.TextField(blank=True, default='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coregis.catobject')),
            ],
        ),
        migrations.CreateModel(
            name='urbanObjectPolygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coregis.urbanobject')),
            ],
        ),
        migrations.CreateModel(
            name='subcatObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcatname', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coregis.catobject')),
            ],
        ),
    ]
