# Generated by Django 3.1.7 on 2021-07-08 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coregis', '0003_catobject_subcatobject_urbanobject_urbanobjectpolygon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcatobject',
            name='category',
        ),
        migrations.RemoveField(
            model_name='urbanobject',
            name='category',
        ),
        migrations.RemoveField(
            model_name='urbanobjectpolygon',
            name='object',
        ),
        migrations.DeleteModel(
            name='catObject',
        ),
        migrations.DeleteModel(
            name='subcatObject',
        ),
        migrations.DeleteModel(
            name='urbanObject',
        ),
        migrations.DeleteModel(
            name='urbanObjectPolygon',
        ),
    ]
