# Generated by Django 3.1.7 on 2021-07-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coregis', '0006_auto_20210708_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresubcatobject',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
