# Generated by Django 3.1.7 on 2021-07-09 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coregis', '0007_coresubcatobject_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreurbanobject',
            name='googlestreeturl',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='coresubcatobject',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcats', to='coregis.corecatobject'),
        ),
    ]
