# Generated by Django 3.1.7 on 2021-07-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coregis', '0008_auto_20210709_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreurbanobject',
            name='photo1',
            field=models.ImageField(blank=True, max_length=255, upload_to=''),
        ),
        migrations.AddField(
            model_name='coreurbanobject',
            name='photo2',
            field=models.ImageField(blank=True, max_length=255, upload_to=''),
        ),
        migrations.AddField(
            model_name='coreurbanobject',
            name='photo3',
            field=models.ImageField(blank=True, max_length=255, upload_to=''),
        ),
    ]
