# Generated by Django 3.1.7 on 2021-07-12 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coregis', '0009_auto_20210709_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreurbanobject',
            name='useradded',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='urbanobjects', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coreurbanobject',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='urbanobjects', to='coregis.coreSubcatObject'),
        ),
    ]
