# Generated by Django 3.1.7 on 2021-07-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coregis', '0010_auto_20210712_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreurbanobject',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
