# Generated by Django 3.1.7 on 2021-07-12 09:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coregis', '0011_coreurbanobject_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreurbanobject',
            name='datetimeadded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
