# Generated by Django 3.1.7 on 2021-07-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coregis', '0012_coreurbanobject_datetimeadded'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreurbanobject',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
