# Generated by Django 3.1.7 on 2021-07-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coregis', '0013_coreurbanobject_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='corecatobject',
            name='icon',
            field=models.CharField(default='object-unknown', max_length=50),
        ),
    ]
