# Generated by Django 3.1.7 on 2021-07-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coregis', '0014_corecatobject_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corecatobject',
            name='icon',
            field=models.CharField(default='object_unknown', max_length=50),
        ),
    ]
