# Generated by Django 3.1.7 on 2021-07-15 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coregis', '0015_auto_20210714_2051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coreurbanobject',
            options={'permissions': [('can_change_not_own_object_record', 'Can change the records that do not belong to current user'), ('can_delete_not_own_object_record', 'Can delete the records that do not belong to current user')]},
        ),
    ]
