# Generated by Django 3.1.7 on 2021-07-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coregis', '0016_auto_20210715_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='corecatobject',
            name='markercolor',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.AddField(
            model_name='coreurbanobject',
            name='rating',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
