# Generated by Django 3.1.7 on 2021-07-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coregis', '0018_auto_20210719_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreurbanobject',
            name='rating',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
    ]
