# Generated by Django 3.1.7 on 2021-10-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coregis', '0019_auto_20210721_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreurbanobject',
            name='subcategories_list',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
