# Generated by Django 3.1.7 on 2021-04-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citytree', '0002_auto_20210408_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
