# Generated by Django 3.1.7 on 2021-04-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citytree', '0004_inspection_tree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='googlestreeturl',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='tree',
            name='speciescomment',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
