# Generated by Django 3.1.7 on 2021-04-08 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citytree', '0005_auto_20210408_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tree',
            name='dateplanted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tree',
            name='googlestreeturl',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='tree',
            name='irrigationmethod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='citytree.irrigationmethod'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='speciescomment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
