# Generated by Django 3.1.7 on 2021-04-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citytree', '0006_auto_20210408_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='recommendations',
            field=models.ManyToManyField(blank=True, null=True, related_name='inspections', to='citytree.CareType'),
        ),
    ]
