# Generated by Django 3.1.7 on 2021-04-14 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citytree', '0007_auto_20210408_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='recommendations',
            field=models.ManyToManyField(blank=True, related_name='inspections', to='citytree.CareType'),
        ),
        migrations.CreateModel(
            name='InspPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(upload_to='trees')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citytree.inspection')),
            ],
        ),
    ]
