# Generated by Django 3.1.7 on 2021-04-19 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citytree', '0010_auto_20210418_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='careactivity',
            name='tree',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='citytree.tree'),
            preserve_default=False,
        ),
    ]
