# Generated by Django 3.1.7 on 2021-04-19 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citytree', '0011_careactivity_tree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree',
            name='irrigationneed',
        ),
    ]
