# Generated by Django 3.1.7 on 2021-04-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citytree', '0013_auto_20210419_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarkname', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='hollow',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='leaningtree',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='rootsdamage',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='sick',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='trunkdamage',
        ),
        migrations.AddField(
            model_name='inspection',
            name='remarks',
            field=models.ManyToManyField(blank=True, related_name='inspections', to='citytree.Remark'),
        ),
    ]
