# Generated by Django 3.1.7 on 2021-04-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citytree', '0014_auto_20210420_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='trunkgirth',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
