# Generated by Django 3.1.7 on 2021-04-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citytree', '0016_auto_20210423_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='lastinsp_recommendations_list',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tree',
            name='lastinsp_recommendations_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tree',
            name='lastinsp_remarks_list',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tree',
            name='lastinsp_remarks_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
