# Generated by Django 3.1.7 on 2021-04-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citytree', '0017_auto_20210423_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='is_geojsoned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='photo1',
            field=models.ImageField(blank=True, upload_to='citytree/images_tree'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='photo2',
            field=models.ImageField(blank=True, upload_to='citytree/images_tree'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='photo3',
            field=models.ImageField(blank=True, upload_to='citytree/images_tree'),
        ),
    ]
