# Generated by Django 3.1.7 on 2021-04-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citytree', '0018_auto_20210427_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careactivity',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careactivity',
            name='executor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
