# Generated by Django 3.1.7 on 2021-05-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citytree', '0021_tree_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=255)),
            ],
        ),
    ]
