# Generated by Django 3.1.7 on 2021-05-06 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citytree', '0022_typespec'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='typespec',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='citytree.typespec'),
            preserve_default=False,
        ),
    ]
