# Generated by Django 3.1.7 on 2021-05-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citytree', '0025_auto_20210506_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='urlinfo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
