# Generated by Django 3.1.7 on 2021-05-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citytree', '0026_species_urlinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
