# Generated by Django 3.1.7 on 2021-05-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citytree', '0027_auto_20210507_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=255)),
                ('pos', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
