# Generated by Django 3.1.7 on 2021-05-07 22:23

import citytree.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citytree', '0029_species_groupspec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='photo1',
            field=models.ImageField(blank=True, upload_to=citytree.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='photo2',
            field=models.ImageField(blank=True, upload_to=citytree.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='photo3',
            field=models.ImageField(blank=True, upload_to=citytree.models.user_directory_path),
        ),
    ]
