# Generated by Django 3.1.7 on 2021-05-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citytree', '0030_auto_20210508_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='googlestreeturl',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
