# Generated by Django 3.1.7 on 2021-05-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citytree', '0031_auto_20210514_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tree',
            name='speciescomment',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
