# Generated by Django 3.1.7 on 2021-05-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citytree', '0032_auto_20210514_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='hexcolor',
            field=models.CharField(default='008000', max_length=6),
        ),
    ]
