# Generated by Django 3.1.7 on 2021-06-15 10:30

import citytree.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citytree', '0033_status_hexcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='photo1',
            field=models.ImageField(blank=True, max_length=255, upload_to=citytree.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='photo2',
            field=models.ImageField(blank=True, max_length=255, upload_to=citytree.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='photo3',
            field=models.ImageField(blank=True, max_length=255, upload_to=citytree.models.user_directory_path),
        ),
    ]
