# Generated by Django 3.1.7 on 2021-07-09 10:59

import citytree.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citytree', '0035_auto_20210615_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='photo1',
            field=models.ImageField(blank=True, max_length=255, upload_to=citytree.models.user_directory_path),
        ),
    ]
