# Generated by Django 3.1.7 on 2021-04-06 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coregis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maneuver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maneuvername', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('coregis.corecity',),
        ),
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('datetime', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('red_light_running', models.BooleanField(default=False)),
                ('priority_traffic_sign', models.BooleanField(default=False)),
                ('lost_control_vehicle', models.BooleanField(default=False)),
                ('drivers_injured', models.PositiveSmallIntegerField(default=0)),
                ('motorcyclists_injured', models.PositiveSmallIntegerField(default=0)),
                ('cyclists_injured', models.PositiveSmallIntegerField(default=0)),
                ('ped_injured', models.PositiveSmallIntegerField(default=0)),
                ('kids_injured', models.PositiveSmallIntegerField(default=0)),
                ('pubtr_passengers_injured', models.PositiveSmallIntegerField(default=0)),
                ('drivers_killed', models.PositiveSmallIntegerField(default=0)),
                ('motorcyclists_killed', models.PositiveSmallIntegerField(default=0)),
                ('cyclists_killed', models.PositiveSmallIntegerField(default=0)),
                ('ped_killed', models.PositiveSmallIntegerField(default=0)),
                ('kids_killed', models.PositiveSmallIntegerField(default=0)),
                ('pubtr_passengers_killed', models.PositiveSmallIntegerField(default=0)),
                ('driver_violation', models.BooleanField(default=False)),
                ('motorcyclist_violation', models.BooleanField(default=False)),
                ('cyclist_violation', models.BooleanField(default=False)),
                ('pedestrian_violation', models.BooleanField(default=False)),
                ('puplic_transport_involved', models.BooleanField(default=False)),
                ('alcohol_or_drug', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='roadaccident.city')),
                ('maneuver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='roadaccident.maneuver')),
            ],
        ),
    ]
