# Generated by Django 3.1.7 on 2021-05-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadaccident', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Injured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injuredname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Killed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('killedname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeViolation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violationname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Violator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violatorname', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='accident',
            name='alcohol_or_drug',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='cyclist_violation',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='cyclists_injured',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='cyclists_killed',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='driver_violation',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='drivers_injured',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='drivers_killed',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='kids_injured',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='kids_killed',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='lost_control_vehicle',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='motorcyclist_violation',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='motorcyclists_injured',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='motorcyclists_killed',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='ped_injured',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='ped_killed',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='pedestrian_violation',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='priority_traffic_sign',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='pubtr_passengers_injured',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='pubtr_passengers_killed',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='red_light_running',
        ),
        migrations.AddField(
            model_name='accident',
            name='injureds',
            field=models.ManyToManyField(blank=True, related_name='accidents', to='roadaccident.Injured'),
        ),
        migrations.AddField(
            model_name='accident',
            name='killeds',
            field=models.ManyToManyField(blank=True, related_name='accidents', to='roadaccident.Killed'),
        ),
        migrations.AddField(
            model_name='accident',
            name='violations_type',
            field=models.ManyToManyField(blank=True, related_name='accidents', to='roadaccident.TypeViolation'),
        ),
        migrations.AddField(
            model_name='accident',
            name='violators',
            field=models.ManyToManyField(blank=True, related_name='accidents', to='roadaccident.Violator'),
        ),
    ]
