# Generated by Django 3.1.7 on 2021-05-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadaccident', '0002_auto_20210512_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accident',
            name='injureds',
        ),
        migrations.RemoveField(
            model_name='accident',
            name='killeds',
        ),
        migrations.AddField(
            model_name='accident',
            name='cyclists_injured',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accident',
            name='cyclists_killed',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accident',
            name='drivers_injured',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accident',
            name='drivers_killed',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accident',
            name='kids_injured',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accident',
            name='kids_killed',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accident',
            name='motorcyclists_injured',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accident',
            name='motorcyclists_killed',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accident',
            name='ped_injured',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accident',
            name='ped_killed',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accident',
            name='pubtr_passengers_injured',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accident',
            name='pubtr_passengers_killed',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Injured',
        ),
        migrations.DeleteModel(
            name='Killed',
        ),
    ]
