# Generated by Django 3.1.7 on 2021-05-14 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roadaccident', '0004_auto_20210513_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accident',
            options={'permissions': [('can_change_not_own_accident_record', 'Can change the records that do not belong to current user'), ('can_delete_not_own_accident_record', 'Can delete the records that do not belong to current user')]},
        ),
        migrations.AddField(
            model_name='accident',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accident',
            name='useradded',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='accidents', to='auth.user'),
            preserve_default=False,
        ),
    ]
