# Generated by Django 3.1.7 on 2021-05-14 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadaccident', '0005_auto_20210514_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accident',
            old_name='puplic_transport_involved',
            new_name='public_transport_involved',
        ),
    ]
