# Generated by Django 3.1.7 on 2021-07-08 10:51

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coregis', '0006_auto_20210708_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='catObject',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('coregis.corecatobject',),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('coregis.corecity',),
        ),
        migrations.CreateModel(
            name='subcatObject',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('coregis.coresubcatobject',),
        ),
        migrations.CreateModel(
            name='urbanObject',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('coregis.coreurbanobject',),
        ),
        migrations.CreateModel(
            name='urbanObjectPolygon',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('coregis.coreurbanobjectpolygon',),
        ),
    ]
