# Generated by Django 3.1.7 on 2021-07-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanobject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadiusTransportMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius', models.PositiveSmallIntegerField()),
                ('description', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
    ]
